= ITE-4: Generic URI Schemes for in-toto
:source-highlighter: pygments
:toc: preamble
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| ITE
| 4

| Title
| Generic URI Schemes for in-toto

| Sponsor
| link:https://github.com/santiagotorres[Santiago Torres-Arias]

| Status
| Draft :speech_balloon:

| Type
| Standards

| Created
| 2019-09-30

|===

[[abstract]]
== Abstract

This ITE proposes a generic Unique Resource Identifier (URI) scheme for in-toto
artifacts. Currently, the in-toto specification only allows for files in the
local filesystem to be the artifacts of link metadata. This ITE also defines the
scheme for a generic URI and provides a behaviour of in-toto implementations
that support generic URIs.

[[specification]]
== Specification

The current in-toto specification must be modified to provide support for the
generic URI schemes. The current specification allows only for files in the
local filesystem to be set as artifacts. With the addition of other entities,
the parts of the specification that directly interact or handle the artifacts
must be updated.

in-toto link metadata files currently look like this:

```
{
    "_type": "link",
    "name": "<NAME>",
    "command": "<COMMAND>",
    "materials": {
        "<PATH>": <HASH>,
        "...": ...
    },
    "products": {
        "<PATH>": <HASH>,
        "...": ...
    },
    "byproducts": {
        "stderr": "<STDERR>",
        "stdout": "<STDOUT>",
        "return-value": "<RETURN-VALUE>"
    },
    "environment": {
        "variables": "<ENV>",
        "filesystem": "<FS>",
        "workdir": "<PWD>"
    }
}
```

The `materials` and `products` fields contain key-value pairs. The URI for each
artifact is its path in the filesystem. With this ITE active, the artifact could
instead have a generic URI which can be resolved to some external resource that
is part of the supply chain. The URI MUST have a fixed structure and MUST
contain all the information necessary for the verifier to resolve if any part of
the verification workflow requires it.

This ITE proposes the following structure for the URI.

`<scheme>:<hier-part>`

This structure is derived from RFC 3986. The `scheme` defines the token or
identifier for the type of resource the URI refers to. It can also contain
other relevant information that indicates how the resource can be accessed. The
`hier-part` identifies the path or location of the resource.

A compliant in-toto system must be capable of generating link metadata with
artifacts that have generic URI references. Therefore, this system must also be
capable of resolving this URI and calculating cryptographic hashes of these
artifacts. It's important to note that the contents of the resource are hashed,
as opposed to the URI itself.

To that end, it's important for a URI scheme to have a single mapping for the
service it refers to. Consider an example of a GitHub specific resource - a pull
request or an issue.

`github+https://github.com/in-toto/in-toto/pull/250`

This can also instead use GitHub's API specific URI to refer to the same data.

`github+https://api.github.com/repos/in-toto/in-toto/pulls/250`

An example of the product field for link metadata with a generic URI is as
follows:

```
"products": {
    "github+https://api.github.com/repos/in-toto/in-toto/pulls/250": {
        "sha256": "7ee0617..."
    },
    "...": ...
}
```

Similarly, an SPDX URI can be used to directly fetch the corresponding documents
from a specified location. For in-toto metadata that exist within SPDX
documents, the URI can also be used to refer to other entities elsewhere in the
document. Resolving such URIs that point to local entities elsewhere in the SPDX
document is an implementation level detail - but it's clear that the URI
contains all the information necessary to identify the entity in that context.

It is important to note that this ITE doesn't mandate any specific generic URI
tokens that all conforming implementations MUST support. Instead, it merely
specifies what any generic URI must look like, and what rules the system MUST
follow.

in-toto artifact rules are a means to specify what artifacts the project owner
expects in every step of the supply chain in the in-toto layout. in-toto
provides the following rules that together attempt to describe the different
types of operations or actions that supply chain functionaries carry out.

*MATCH Rule*

`MATCH <pattern> [IN <source-path-prefix>] WITH (MATERIALS|PRODUCTS) [IN <destination-path-prefix>] FROM <step>`

The Match rule is a convenient way to match artifacts (either in materials or
products depending on where the rule is specified) with artifacts from other
steps in the supply chain, allowing owners to establish a flow of artifacts
between steps in the software supply chain.

The current verification workflow for the `MATCH` rule compares the
cryptographic hashes of the relevant artifacts from the respective link files.
This is a straightforward comparison and does not entail resolving the URIs in
any form. The `IN` clauses which are used to specify path prefixes are
subtracted from the URI strings. Therefore, we conclude that the functioning of
the rule doesn't change with this ITE. An example `MATCH` rule with generic URIs
is as follows:

`MATCH pull/250 IN github+https://github.com/in-toto/in-toto/ WITH PRODUCTS IN
github+https://github.com/in-toto/in-toto-golang/pull/ FROM merge-go-repository`

*Other artifact rules*

in-toto provides several other artifact rules - specifically `ALLOW`,
`DISALLOW`, `CREATE`, `DELETE`, `REQUIRE`, and `MODIFY`. These rules perform
different checks by verifying if artifacts matching the pattern occur or do not
occur in the materials or products sections of the relevant link. This does not
involve resolving the pattern or URI into the artifact itself, and so this ITE
does not affect the working of these rules.

[[motivation]]
== Motivation

ITE 4 is motivated by the following use cases.

==== Use Case 1: SPDX Document Identifiers

The Software Package Data Exchange (SPDX) is an open standard for communicating
software bill of material information such as components, licenses, copyrights,
and security references. Each document is a comprehensive report that describes
a software package in detail. They're composed of several entities that have
unique identifiers. These identifiers can be used in in-toto metadata embedded
in SPDX documents to refer to the respective entities.

===== in-toto link attestation for packaging SPDX files into an SPDX package

An in-toto attestation can be bundled into an SPDX document to show the chain of
custody for the elements the SPDX document refers to. Here, we see how
provenance can be attested to for File and Package entities in an SPDX document.

```
{
    "_type": "link",
    "name": "package-ghostscript-9.21.tar.gz",
    "command": "<COMMAND>",
    "materials": {
        "spdx:SPDXRef-141-File-83pv-RKSJ-H-d51620a4d7d9aeca3a1cbe5ef201513f98d65f98": <HASH>,
        "spdx:SPDXRef-271-File-AUTHORS.md-109c93392646b4d55e3ca62c5b578a9ac7cc159f": <HASH>,
        "...": "..."
    },
    "products": {
        "spdx:SPDXRef-Pkg-ghostscript-9.21.tar.gz-6f60d7fcb5eef6a8bec5abedf21c6a7008a8c0c7": <HASH>
    },
    "byproducts": {
        "stderr": "",
        "stdout": "",
        "return-value": ""
    },
    "environment": {
        "variables": "",
        "filesystem": "",
        "workdir": ""
    }
}
```

==== Use Case 2: GitHub Entities

GitHub has more abstract entities such as Pull Requests and Issues. These
entities can be referred to directly using the URI schemes proposed in this ITE
and help provide attestations about these artifacts. Consider:

===== in-toto link attestation for merging a pull request into `master`

A pull request is a proposal to make changes to a repository. Changes are either
made on a separate branch on the same repository or a branch on a fork of the
repository and the pull request is a proposal to merge these changes into the
main repository. The act of merging a pull request is performed by an authorized
member of the development team of the repository.

By default, the commits that make up the change are integrated into the target
branch and an additional merge commit is created to indicate the act of merging.
It's also possible to merge a pull request without creating a separate merge
commit. The attestation could look something like:

```
{
    "_type": "link",
    "name": "merge-pull-request-250",
    "command": "",
    "materials": {
        "github+https://github.com/in-toto/in-toto/pull/250": <HASH>
    },
    "products": {
        "github+https://github.com/in-toto/in-toto/commit/f1c5d201887e226cadac5792a203ac3eae347add": <HASH>
    },
    "byproducts": {
        "stderr": "",
        "stdout": "",
        "return-value": ""
    },
    "environment": {
        "variables": "",
        "filesystem": "",
        "workdir": ""
    }
}
```

This step is accepting the pull request as a material and is recording the merge
commit as a product.

===== in-toto link attesation for GitHub Actions building from a merge commit

GitHub Actions can be used to set up a workflow for continuous integration (CI).
Workflows can be triggered on push and an attestation can be generated for the
resulting build and CI report.


```
{
    "_type": "link",
    "name": "github-actions-build-pull-request-250",
    "command": "",
    "materials": {
        "github+https://github.com/in-toto/in-toto/commit/f1c5d201887e226cadac5792a203ac3eae347add": <HASH>
    },
    "products": {
        "github+https://github.com/in-toto/in-toto/commit/f1c5d201887e226cadac5792a203ac3eae347add/checks?check_suite_id=<ID>": <HASH>
    },
    "byproducts": {
        "stderr": "",
        "stdout": "",
        "return-value": ""
    },
    "environment": {
        "variables": "",
        "filesystem": "",
        "workdir": ""
    }
}
```

[[reasoning]]
== Reasoning

This ITE proposes a change in the URI scheme of artifacts in in-toto metadata.
The proposed change closely matches the URI structure laid out in RFC 3986. The
URI structure proposed in that document is widely accepted and is versatile
enough to allow for a wide variety of references. It is also easy to implement
and extend support for due to the presence of a large number of standard
libraries.

[[backwards-compatibility]]
== Backwards Compatibility

If in-toto metadata is generated using an implementation of in-toto conforming
to this ITE, verification using a non-conforming implementation will likely
fail. It is still possible for verification to continue if the inspections don't
use generic URIs. This is because the layout may contain inspections that use
generic URIs.

However, a conforming implementation should be capable of verifying in-toto
metadata generated using a non-conforming implementation, as an ITE-4 conforming
system must also conform to the actual in-toto specification.

It's also possible two conforming systems are unable to verify the other's
in-toto metadata as they're unaware of how to resolve certain URI tokens used by
the other. This is again because of the possibility of inspections containing
URIs that the other system is unable to resolve and calculate cryptographic
information for.

[[security]]
== Security

It's important to note that filepaths are a form of URIs too, and can be
represented with the `scheme` `file://`. We have also discovered that `MATCH`
and other artifact rules use only the URI strings themselves to find the
appropriate entries in the link metadata. The changes proposed in this ITE,
therefore, have no effect on the security guarantees made by the in-toto
specification.

Implementing systems that conform to this ITE must, however, be careful with how
they compute cryptographic hashes of abstract entities.

[[infrastructure-requirements]]
== Infrastructure Requirements

This ITE proposes no infrastructure changes.

[[testing]]
== Testing

In an in-toto system conforming to this ITE, it is important to test:

- that all the artifact rules behave as described in the specification
- that cryptographic hashes of data in abstract entities change with changes in
in the data - in effect, this would test how the data is transformed into a form
that can be hashed

[[prototype-implementation]]
== Prototype Implementation

This ITE currently proposes no prototypes.

[[references]]
== References

* link:https://tools.ietf.org/html/rfc3986[Uniform Resource Identifier (URI): Generic Syntax]
* link:https://github.com/in-toto/docs/blob/master/in-toto-spec.md[in-toto Specification]
* link:https://pypi.org/project/rfc3986/[RFC 3986 library for Python]
