= ITE-5: Replace signature envelope with SSL signing spec
:source-highlighter: pygments
:toc: preamble
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| ITE
| 5

| Title
| Replace signature envelope with SSL signing spec

| Sponsor
| link:https://github.com/santiagotorres[Santiago Torres]

| Status
| Draft 💬


| Type
| Standards

| Created
| 2020-09-28

|===

[[abstract]]
== Abstract

This link:https://github.com/in-toto/ITE[in-toto enhancement (ITE)] proposes
removing the in-toto signature scheme requirements, and allow users to adopt the
signature envelope that better fits their ecosystem. This has the following
general benefits:

1. avoid mandating an ad-hoc signing specification for in-toto; and
2. allow for implementers to propose different signing specifications.

In addition, this ITE makes a recommendation to use the
link:http://github.com/secure-systems-lab/signing-spec[SSL Signing Spec]. This
has the following benefits over the current state:

1. Avoids canonicalization for security reasons (i.e., to not parse untrusted input) 
2. Reduces the possibility of misinterpretation of the payload. The serialized payload is encoded as a string and verified by the recipient before de-serializing.

[[specification]]
== Specification

The specification adopted will be the SSL signing spec, as linked above. As
such, we defer to that document to describe the specifics of signature
generation and verification.

The envelope's `payloadType` is either:

* `https://in-toto.io/Link/v1+json` (for links)
* `https://in-toto.io/Layout/v1+json` (for layouts)

The `payload` is the JSON serialization of the message, equivalent to the
`signed` object in the current format.

[[motivation]]
== Motivation

The early motivations for in-toto to use the current envelope were to allow for
our sister project, TUF, to transparently use the same crypto provider. The
reasoning back then is that we would maximize code reuse, and allow for users
of both solutions to easily integrate them.

However, as time has shown, keeping these two separately-specified signature
envelopes (i.e., one for TUF and one for in-toto) synchronized is rather difficult. As time
passes, and due to the interactions in each community, the signature envelopes
evolve to better fit their user-bases. Adopting a common source of truth (i.e.,
a separate signature specification) should help increase cohesion between
projects while maintaining the original goal of code-reuse and transparent
integration.

In addition, keeping the signature envelope specification *outside* of the
current in-toto specification will also simplify the specification, which can
now only focus on describing in-toto specifics, rather than cryptographic
building blocks.

[[reasoning]]
== Reasoning

Our goal was to adopt a signature envelope that is as simple and foolproof as
possible. Alternatives such as link:https://tools.ietf.org/html/rfc7515[JWS] are
extremely complex and error-prone, while others such as
link:https://github.com/paragonie/paseto/blob/master/docs/01-Protocol-Versions/Version2.md#sig[PASETO]
are overly specific. (Both are also JSON-specific.) We believe the SSL signing
spec strikes the right balance of simplicity, usefulness, and security. 

Further, the SSL signing spec is a "natural evolution" of the current signature
envelope, which was defined in both the TUF and in-toto specifications. As such,
it allows for a transparent upgrade via their cryptographic provider,
link:https://github.com/secure-systems-lab/securesystemslib[securesystemslib].

Further information on the reasoning behind the envelope's specifics is provided in the link:https://github.com/secure-systems-lab/signing-spec[signing specification] repository

[[backwards-compatibility]]
== Backwards Compatibility

Implementations should continue to support old-style envelope as well as
new-style SSL Signing Spec envelopes.

[[security]]
== Security

At first sight this proposal is central to security, yet the actual
contribution is to allow for a signature provider to be disaggregated from the
specification. As such, no supply-chain security properties are removed from
the system through this ITE.

The adoption of SSL signing spec slightly improves the security stance of
implementations because they are no longer parsing untrusted input.

[[infrastructure-requirements]]
== Infrastructure Requirements

Since this is a change in the metadata format, no infrastructure requirements
exist.


[[prototype-implementation]]
== Prototype Implementation

See
link:https://github.com/secure-systems-lab/signing-spec/blob/master/reference_implementation.ipynb[reference_implementation.ipynb]
for an implementation of the envelope itself.

[[testing]]
== Testing

The test-suite should include loading/generating both new-style SSL signing spec
metadata as well old-style metadata.

[[references]]
== References

* link:http://gibson042.github.io/canonicaljson-spec/[Canonical JSON]
* link:https://tools.ietf.org/html/rfc7515[JWS]
* link:https://github.com/paragonie/paseto/blob/master/docs/01-Protocol-Versions/Version2.md#sig[PASETO]
