= ITE-5: Disassociate signature envelope specification from in-toto
:source-highlighter: pygments
:toc: preamble
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| ITE
| 5

| Title
| Disassociate signature envelope specification from in-toto

| Sponsor
| link:https://github.com/santiagotorres[Santiago Torres]

| Status
| Accepted

| Type
| Standards

| Created
| 2020-09-28

|===

[[abstract]]
== Abstract


This link:https://github.com/in-toto/ITE[in-toto enhancement (ITE)] proposes
disassociating the signature envelope from the in-toto specification, enabling
implementers to use an envelope of their choice given that it supports certain
security properties. Further, this ITE recommends the use of the
link:https://github.com/secure-systems-lab/dsse[Dead Simple Signing Envelope (DSSE)].

If an implementation is using the old signature envelope, it SHOULD be
deprecated, with support for it removed after a sensible transition period.

[[specification]]
== Specification

The in-toto specification currently (as of August 2021) uses a custom signature
wrapper. At the time of authoring this document, the Python reference
implementation also emits in-toto metadata using this wrapper.

However, in-toto adopters may wish to generate in-toto metadata using other
formats, perhaps in wireline formats they already support. It is possible to
get the benefits of in-toto while still using other wrappers, given that they
provide certain important properties. These properties dictate that signature
wrappers:

* SHOULD include an authenticated payload type
* SHOULD avoid depending on canonicalization for security
* SHOULD NOT require the verifier to parse the payload before verifying
* SHOULD NOT require the inclusion of signing key algorithms in the signature
* MUST support the inclusion of multiple signatures in a file
* SHOULD support a hint indicating what signing key was used, i.e., a KEYID

The current signature wrapper requires canonicalization, which means that
untrusted inputs are parsed. It also does not include an authenticated
payload type, which can lead to misinterpretation of the payload. As a
result, this ITE recommends, but does not mandate, the use of the
Dead Simple Signing Envelope v1.0. The implementations maintained by the
in-toto team MUST switch to using DSSE by default while providing a
transition period during which both wrappers are supported. For more
information, please refer to the
link:#backwards-compatibility[Backwards Compatibility] section.

The envelope's `payloadType` is `application/vnd.in-toto+json` for both links
and layouts. This means that the payload is expected to be a JSON file with a
`_type` field. The envelope's `payload` is the JSON serialization of the
message, equivalent to the `signed` object in the current format.

[[pseudocode]]
=== Pseudocode for in-toto's Reference Implementation

[[pseudocode-transition]]
==== During Transition Period

Inputs:

*   `file`: JSON-encoded link or layout
*   `recognizedSigners`: collection of (`name`, `publicKey`) pairs

Outputs:

*   `message`: the signed message as an implementation-language-specific object
*   `signers`: set of recognized names that have signed the message

Steps:

*   `envelope` := JsonDecode(`file`); raise error if the decoding fails
*   If `envelope.payload` exists (new-style envelope):
    **  If `payloadType` != `application/vnd.in-toto+json`, raise error
    **  `preauthEncoding` := PAE(UTF8(`envelope.payloadType`),
        `envelope.payload`) as per DSSE
    **  `signers` := set of `name` for which Verify(`preauthEncoding`,
        `signature.sig`, `publicKey`) succeeds, for all combinations of
        (`signature`) in `envelope.signatures` and (`name`, `publicKey`) in
        `recognizedSigners`
    **  `message` := JsonDecode(`envelope.payload`)
*   Else if `envelope.signed` exists (old-style envelope):
    **  `preauthEncoding` := CanonicalJsonEncode(`envelope.signed`)
    **  `signers` := set of `name` for which Verify(`preauthEncoding`,
        `signature.sig`, `publicKey`) succeeds, for all combinations of
        (`signature`) in `envelope.signatures` and (`name`, `publicKey`) in
        `recognizedSigners`
    **  `message` := `envelope.signed`
*   Else, raise error
*   Raise error if `signers` is empty
*   Return `message` and `signers`

[[pseudocode-dsse-only]]
==== After Transition Period

Inputs:

*   `file`: JSON-encoded link or layout
*   `recognizedSigners`: collection of (`name`, `publicKey`) pairs

Outputs:

*   `message`: the signed message as an implementation-language-specific object
*   `signers`: set of recognized names that have signed the message

Steps:

*   `envelope` := JsonDecode(`file`); raise error if the decoding fails
*   If `envelope.payload` exists:
    **  If `payloadType` != `application/vnd.in-toto+json`, raise error
    **  `preauthEncoding` := PAE(UTF8(`envelope.payloadType`),
        `envelope.payload`) as per DSSE
    **  `signers` := set of `name` for which Verify(`preauthEncoding`,
        `signature.sig`, `publicKey`) succeeds, for all combinations of
        (`signature`) in `envelope.signatures` and (`name`, `publicKey`) in
        `recognizedSigners`
    **  `message` := JsonDecode(`envelope.payload`)
*   Else, raise error
*   Raise error if `signers` is empty
*   Return `message` and `signers`


[[motivation]]
== Motivation

The early motivations for in-toto to use the current envelope were to allow for
our sister project, TUF, to transparently use the same crypto provider. The
reasoning back then is that we would maximize code reuse, and allow for users
of both solutions to easily integrate them.

However, as time has shown, keeping these two separately-specified signature
envelopes (i.e., one for TUF and one for in-toto) synchronized is rather difficult. As time
passes, and due to the interactions in each community, the signature envelopes
evolve to better fit their user-bases. Adopting a common source of truth (i.e.,
a separate signature specification) should help increase cohesion between
projects while maintaining the original goal of code-reuse and transparent
integration.

In addition, keeping the signature envelope specification *outside* of the
current in-toto specification will also simplify the specification, which can
now only focus on describing in-toto specifics, rather than cryptographic
building blocks.

[[reasoning]]
== Reasoning

Our goal was to enable adopters to use in-toto without also committing to
a single signature wrapper defined in the specification. Further, for our
reference implementations, we wanted the signature envelope to be as simple and
foolproof as possible. DSSE checked those boxes, while also being a "natural
evolution" of the existing signature wrapper. For further information
on the reasoning behind DSSE, please refer to the
link:https://github.com/secure-systems-lab/dsse/blob/master/background.md[Background section]
of its specification.

[[backwards-compatibility]]
== Backwards Compatibility

Implementations should continue to support old-style envelope as well as
new-style envelopes during the transition period. Implementators are free to
determine the length of this period, and MUST communicate this clearly to their
users using their standard channels. For example, the in-toto reference
implementation MUST use its roadmaps to define a transition period and set
a date for when it will drop support for the old style envelopes entirely.

During the transition period, implementers MAY use the pseudocode defined
link:#pseudocode-transition[above], while swapping out the DSSE specific
processing to match their chosen signature wrappers.

[[security]]
== Security

At first sight this proposal is central to security, yet the actual
contribution is to allow for a signature provider to be disaggregated from the
specification. As such, no supply-chain security properties are removed from
the system through this ITE.

The adoption of DSSE slightly improves the security stance of our reference
implementations because they are no longer parsing possibly untrusted input.

[[infrastructure-requirements]]
== Infrastructure Requirements

Since this is a change in the metadata format, no infrastructure requirements
exist.


[[prototype-implementation]]
== Prototype Implementation

None yet.

[[testing]]
== Testing

The test-suites of the reference implementations should include
loading / generating both new-style DSSE metadata as well old-style metadata.

[[references]]
== References

* link:http://gibson042.github.io/canonicaljson-spec/[Canonical JSON]
* link:https://tools.ietf.org/html/rfc7515[JWS]
* link:https://github.com/paragonie/paseto/blob/master/docs/01-Protocol-Versions/Version2.md#sig[PASETO]
