= ITE-1: in-toto Enhancement Format
:source-highlighter: pygments
:toc: preamble
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| ITE
| 0000

| Title
| in-toto Enhancement template

| Sponsor
| link:https://github.com/yourusernamehere[John Doe]

| Status
| Active :smile:

| Type
| Process

| Created
| yyyy-mm-dd

|===


[[abstract]]
== Abstract

An abstract of approximately 200 words describing the technical issue
addressed.

[[specification]]
== Specification

The specification text here. Describe in depth the feature that you may want to
integrate.

[[motivation]]
== Motivation

Here, describe the rationale behind the changes you are proposing.

[[reasoning]]
== Reasoning

Here, describe why the decisions you made in the specification make sense.

[[backwards-compatibility]]
== Backwards Compatibility

Describe how these changes will affect backwards compatibility and how you plan
on mitigating the effects of these.

[[security]]
== Security

Provide a security analysis of these changes including the threat model
considered (and how it differs from the existing threat model for in-toto).
Mention the security impact of adding these changes to in-toto.

[[infrastructure-requirements]]
== Infrastructure Requirements

If your changes require additional infrastructure, describe it here. Include
potential costs incurred considering both time and money.

[[testing]]
== Testing

If your implementation includes code, include this section describing how your
changes will be tested.

[[prototype-implementation]]
== Prototype Implementation

If your ITE includes code changes, provide some links to the prototype
implementation of these changes.

[[references]]
== References

=== example references

* link:http://www.ietf.org/rfc.html[IETF RFC]
